/**
 * Script para importar locais de votação com bairros para Parnaíba
 * Dados extraídos da planilha "zona x seçao.xlsx" - 408 seções únicas
 * Execute com: npx ts-node src/scripts/seed-voting-locations-updated.ts
 */

import { DataSource } from 'typeorm';
import { VotingLocation } from '../election-results/voting-location.entity';

// Dados extraídos da planilha - Mapeamento Seção -> Bairro (408 seções únicas)
const votingLocationsData = [
    { zone: 4, section: 1, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 1', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 2, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 2', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 3, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 3', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 4, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 4', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 5, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 5', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 6, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 6', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 7, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 7', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 8, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 8', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 9, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 9', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 10, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 10', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 11, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 11', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 12, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 12', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 13, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 13', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 14, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 14', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 15, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 15', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 16, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 16', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 17, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 17', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 18, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 18', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 19, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 19', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 20, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 20', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 21, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 21', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 22, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 22', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 23, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 23', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 24, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 24', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 25, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 25', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 26, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 26', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 27, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 27', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 28, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 28', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 29, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 29', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 30, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 30', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 31, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 31', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 32, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 32', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 33, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 33', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 34, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 34', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 35, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 35', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 36, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 36', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 37, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 37', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 38, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 38', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 39, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 39', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 40, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 40', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 41, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 41', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 42, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 42', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 43, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 43', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 44, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 44', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 45, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 45', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 46, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 46', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 47, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 47', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 48, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 48', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 49, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 49', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 50, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 50', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 51, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 51', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 52, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 52', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 53, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 53', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 54, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 54', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 55, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 55', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 56, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 56', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 57, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 57', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 58, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 58', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 59, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 59', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 60, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 60', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 61, neighborhood: 'CATANDUVAS', locationName: 'LOCAL SECAO 61', address: 'BAIRRO CATANDUVAS' },
    { zone: 4, section: 62, neighborhood: 'CATANDUVAS', locationName: 'LOCAL SECAO 62', address: 'BAIRRO CATANDUVAS' },
    { zone: 4, section: 63, neighborhood: 'CATANDUVAS', locationName: 'LOCAL SECAO 63', address: 'BAIRRO CATANDUVAS' },
    { zone: 4, section: 64, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 64', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 65, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 65', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 66, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 66', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 67, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 67', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 68, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 68', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 69, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 69', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 70, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 70', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 71, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 71', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 72, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 72', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 73, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 73', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 74, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 74', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 75, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 75', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 76, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 76', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 77, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 77', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 78, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 78', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 79, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 79', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 80, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 80', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 81, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 81', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 82, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 82', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 83, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 83', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 84, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 84', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 85, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 85', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 86, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 86', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 87, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 87', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 88, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 88', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 89, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 89', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 90, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 90', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 91, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 91', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 92, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 92', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 93, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 93', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 94, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 94', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 95, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 95', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 96, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 96', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 97, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 97', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 98, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 98', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 99, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 99', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 100, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 100', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 101, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 101', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 102, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 102', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 103, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 103', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 104, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 104', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 105, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 105', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 106, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 106', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 107, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 107', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 108, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 108', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 109, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 109', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 110, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 110', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 111, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 111', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 112, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 112', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 113, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 113', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 114, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 114', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 115, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 115', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 116, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 116', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 117, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 117', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 118, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 118', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 119, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 119', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 120, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 120', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 121, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 121', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 122, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 122', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 127, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 127', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 128, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 128', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 129, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 129', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 130, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 130', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 131, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 131', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 132, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 132', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 133, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 133', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 134, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 134', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 135, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 135', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 136, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 136', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 137, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 137', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 138, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 138', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 139, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 139', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 140, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 140', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 141, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 141', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 145, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 145', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 146, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 146', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 147, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 147', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 148, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 148', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 149, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 149', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 150, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 150', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 151, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 151', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 152, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 152', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 153, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 153', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 154, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 154', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 155, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 155', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 156, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 156', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 157, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 157', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 158, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 158', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 159, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 159', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 160, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 160', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 161, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 161', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 162, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 162', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 163, neighborhood: 'MENDONCA CLARK', locationName: 'LOCAL SECAO 163', address: 'BAIRRO MENDONCA CLARK' },
    { zone: 4, section: 164, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 164', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 166, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 166', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 167, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 167', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 168, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 168', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 169, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 169', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 170, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 170', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 171, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 171', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 172, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 172', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 173, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 173', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 174, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 174', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 175, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 175', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 176, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 176', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 177, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 177', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 178, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 178', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 179, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 179', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 180, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 180', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 181, neighborhood: 'TABOLEIRO', locationName: 'LOCAL SECAO 181', address: 'BAIRRO TABOLEIRO' },
    { zone: 4, section: 182, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 182', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 183, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 183', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 184, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 184', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 185, neighborhood: 'CATANDUVAS', locationName: 'LOCAL SECAO 185', address: 'BAIRRO CATANDUVAS' },
    { zone: 4, section: 186, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 186', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 187, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 187', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 188, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 188', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 189, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 189', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 190, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 190', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 191, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 191', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 192, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 192', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 193, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 193', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 194, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 194', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 195, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 195', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 196, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 196', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 197, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 197', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 198, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 198', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 199, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 199', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 200, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 200', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 201, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 201', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 202, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 202', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 203, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 203', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 204, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 204', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 205, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 205', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 206, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 206', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 207, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 207', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 208, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 208', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 209, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 209', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 210, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 210', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 211, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 211', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 212, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 212', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 213, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 213', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 214, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 214', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 215, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 215', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 216, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 216', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 217, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 217', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 218, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 218', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 219, neighborhood: 'IGARACU', locationName: 'LOCAL SECAO 219', address: 'BAIRRO IGARACU' },
    { zone: 4, section: 220, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 220', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 221, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 221', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 222, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 222', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 223, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 223', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 224, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 224', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 225, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 225', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 226, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 226', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 227, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 227', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 228, neighborhood: 'LAGOA DA PRATA', locationName: 'LOCAL SECAO 228', address: 'BAIRRO LAGOA DA PRATA' },
    { zone: 4, section: 229, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 229', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 230, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 230', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 231, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 231', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 232, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 232', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 233, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 233', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 234, neighborhood: 'CATANDUVAS', locationName: 'LOCAL SECAO 234', address: 'BAIRRO CATANDUVAS' },
    { zone: 4, section: 235, neighborhood: 'SABIAZAL', locationName: 'LOCAL SECAO 235', address: 'BAIRRO SABIAZAL' },
    { zone: 4, section: 236, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 236', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 237, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 237', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 238, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 238', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 239, neighborhood: 'TABOLEIRO', locationName: 'LOCAL SECAO 239', address: 'BAIRRO TABOLEIRO' },
    { zone: 4, section: 240, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 240', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 241, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 241', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 242, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 242', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 243, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 243', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 244, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 244', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 245, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 245', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 246, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 246', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 247, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 247', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 248, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 248', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 249, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 249', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 250, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 250', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 251, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 251', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 252, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 252', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 253, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 253', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 254, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 254', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 255, neighborhood: 'IGARACU', locationName: 'LOCAL SECAO 255', address: 'BAIRRO IGARACU' },
    { zone: 4, section: 256, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 256', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 257, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 257', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 258, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 258', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 259, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 259', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 260, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 260', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 261, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 261', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 262, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 262', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 263, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 263', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 264, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 264', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 265, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 265', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 266, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 266', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 267, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 267', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 268, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 268', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 269, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 269', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 270, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 270', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 271, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 271', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 272, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 272', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 273, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 273', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 274, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 274', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 275, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 275', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 276, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 276', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 277, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 277', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 278, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 278', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 279, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 279', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 280, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 280', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 281, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 281', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 282, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 282', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 283, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 283', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 284, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 284', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 285, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 285', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 286, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 286', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 287, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 287', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 288, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 288', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 289, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 289', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 290, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 290', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 291, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 291', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 292, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 292', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 293, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 293', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 294, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 294', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 295, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 295', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 296, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 296', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 297, neighborhood: 'IGARACU', locationName: 'LOCAL SECAO 297', address: 'BAIRRO IGARACU' },
    { zone: 4, section: 298, neighborhood: 'SABIAZAL', locationName: 'LOCAL SECAO 298', address: 'BAIRRO SABIAZAL' },
    { zone: 4, section: 299, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 299', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 300, neighborhood: 'LAGOA DA PRATA', locationName: 'LOCAL SECAO 300', address: 'BAIRRO LAGOA DA PRATA' },
    { zone: 4, section: 301, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 301', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 302, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 302', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 303, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 303', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 304, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 304', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 305, neighborhood: 'IGARACU', locationName: 'LOCAL SECAO 305', address: 'BAIRRO IGARACU' },
    { zone: 4, section: 306, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 306', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 307, neighborhood: 'PLANALTO', locationName: 'LOCAL SECAO 307', address: 'BAIRRO PLANALTO' },
    { zone: 4, section: 308, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 308', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 309, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 309', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 310, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 310', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 311, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 311', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 312, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 312', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 313, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 313', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 314, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 314', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 315, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 315', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 316, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 316', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 317, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 317', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 318, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 318', address: 'BAIRRO SAO JOSE' },
    { zone: 4, section: 319, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 319', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 320, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 320', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 321, neighborhood: 'TABOLEIRO', locationName: 'LOCAL SECAO 321', address: 'BAIRRO TABOLEIRO' },
    { zone: 4, section: 322, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 322', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 323, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 323', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 324, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 324', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 325, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 325', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 326, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 326', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 327, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 327', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 328, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 328', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 329, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 329', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 330, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 330', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 331, neighborhood: 'FREI HIGINO', locationName: 'LOCAL SECAO 331', address: 'BAIRRO FREI HIGINO' },
    { zone: 4, section: 332, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 332', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 333, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 333', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 334, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 334', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 335, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 335', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 336, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 336', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 337, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 337', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 338, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 338', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 339, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 339', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 340, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 340', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 341, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 341', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 342, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 342', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 343, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 343', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 345, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 345', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 353, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 353', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 355, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 355', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 357, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 357', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 378, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 378', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 392, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 392', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 401, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 401', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 402, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 402', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 403, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 403', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 404, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 404', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 405, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 405', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 406, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 406', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 407, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 407', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 408, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 408', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 409, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 409', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 410, neighborhood: 'JOAO XXIII', locationName: 'LOCAL SECAO 410', address: 'BAIRRO JOAO XXIII' },
    { zone: 4, section: 411, neighborhood: 'PLANALTO', locationName: 'LOCAL SECAO 411', address: 'BAIRRO PLANALTO' },
    { zone: 4, section: 412, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 412', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 413, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 413', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 414, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 414', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 415, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 415', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 416, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 416', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 417, neighborhood: 'NOSSA SENHORA DO CARMO', locationName: 'LOCAL SECAO 417', address: 'BAIRRO NOSSA SENHORA DO CARMO' },
    { zone: 4, section: 418, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 418', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 419, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 419', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 420, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 420', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 421, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 421', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 422, neighborhood: 'PINDORAMA', locationName: 'LOCAL SECAO 422', address: 'BAIRRO PINDORAMA' },
    { zone: 4, section: 423, neighborhood: 'JOAZ SOUZA', locationName: 'LOCAL SECAO 423', address: 'BAIRRO JOAZ SOUZA' },
    { zone: 4, section: 424, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 424', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 425, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 425', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 426, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 426', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 427, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 427', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 428, neighborhood: 'ZONA RURAL', locationName: 'LOCAL SECAO 428', address: 'BAIRRO ZONA RURAL' },
    { zone: 4, section: 429, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 429', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 430, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 430', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 431, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 431', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 432, neighborhood: 'CAMPOS', locationName: 'LOCAL SECAO 432', address: 'BAIRRO CAMPOS' },
    { zone: 4, section: 433, neighborhood: 'NOVA PARNAIBA', locationName: 'LOCAL SECAO 433', address: 'BAIRRO NOVA PARNAIBA' },
    { zone: 4, section: 434, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 434', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 435, neighborhood: 'NOSSA SENHORA DE FATIMA', locationName: 'LOCAL SECAO 435', address: 'BAIRRO NOSSA SENHORA DE FATIMA' },
    { zone: 4, section: 436, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 436', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 437, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 437', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 438, neighborhood: 'PLANALTO', locationName: 'LOCAL SECAO 438', address: 'BAIRRO PLANALTO' },
    { zone: 4, section: 439, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 439', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 440, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 440', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 441, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 441', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 442, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 442', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 443, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 443', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 444, neighborhood: 'IGARACU', locationName: 'LOCAL SECAO 444', address: 'BAIRRO IGARACU' },
    { zone: 4, section: 445, neighborhood: 'ROSAPOLIS', locationName: 'LOCAL SECAO 445', address: 'BAIRRO ROSAPOLIS' },
    { zone: 4, section: 446, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 446', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 447, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 447', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 448, neighborhood: 'FREI HIGINO', locationName: 'LOCAL SECAO 448', address: 'BAIRRO FREI HIGINO' },
    { zone: 4, section: 449, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 449', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 450, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 450', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 451, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 451', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 452, neighborhood: 'SAO VICENTE DE PAULA', locationName: 'LOCAL SECAO 452', address: 'BAIRRO SAO VICENTE DE PAULA' },
    { zone: 4, section: 453, neighborhood: 'RODOVIARIA', locationName: 'LOCAL SECAO 453', address: 'BAIRRO RODOVIARIA' },
    { zone: 4, section: 454, neighborhood: 'SABIAZAL', locationName: 'LOCAL SECAO 454', address: 'BAIRRO SABIAZAL' },
    { zone: 4, section: 455, neighborhood: 'PLANALTO', locationName: 'LOCAL SECAO 455', address: 'BAIRRO PLANALTO' },
    { zone: 4, section: 456, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 456', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 457, neighborhood: 'BOA ESPERANCA', locationName: 'LOCAL SECAO 457', address: 'BAIRRO BOA ESPERANCA' },
    { zone: 4, section: 458, neighborhood: 'CENTRO', locationName: 'LOCAL SECAO 458', address: 'BAIRRO CENTRO' },
    { zone: 4, section: 459, neighborhood: 'SAO BENEDITO', locationName: 'LOCAL SECAO 459', address: 'BAIRRO SAO BENEDITO' },
    { zone: 4, section: 460, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 460', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 461, neighborhood: 'FLORIOPOLIS', locationName: 'LOCAL SECAO 461', address: 'BAIRRO FLORIOPOLIS' },
    { zone: 4, section: 462, neighborhood: 'SANTA LUZIA', locationName: 'LOCAL SECAO 462', address: 'BAIRRO SANTA LUZIA' },
    { zone: 4, section: 463, neighborhood: 'PIAUI', locationName: 'LOCAL SECAO 463', address: 'BAIRRO PIAUI' },
    { zone: 4, section: 464, neighborhood: 'ALTO SANTA MARIA', locationName: 'LOCAL SECAO 464', address: 'BAIRRO ALTO SANTA MARIA' },
    { zone: 4, section: 465, neighborhood: 'ROSAPOLIS', locationName: 'LOCAL SECAO 465', address: 'BAIRRO ROSAPOLIS' },
    { zone: 4, section: 466, neighborhood: 'DIRCEU ARCOVERDE', locationName: 'LOCAL SECAO 466', address: 'BAIRRO DIRCEU ARCOVERDE' },
    { zone: 4, section: 467, neighborhood: 'SAO JOSE', locationName: 'LOCAL SECAO 467', address: 'BAIRRO SAO JOSE' },
];

async function seedVotingLocations() {
    const dataSource = new DataSource({
        type: 'postgres',
        host: process.env.DATABASE_HOST || '144.126.137.156',
        port: parseInt(process.env.DATABASE_PORT || '5437'),
        username: process.env.DATABASE_USER || 'postgres',
        password: process.env.DATABASE_PASSWORD || 'T1fpOr8Kw7KQEpU781gm9NWy7#',
        database: process.env.DATABASE_NAME || 'admin',
        entities: [VotingLocation],
        synchronize: false,
    });

    await dataSource.initialize();
    console.log('Conectado ao banco de dados');

    const repository = dataSource.getRepository(VotingLocation);

    // Limpar tabela antes
    await repository.clear();
    console.log('Tabela voting_locations limpa');

    // Inserir dados em batch
    let inserted = 0;
    for (const loc of votingLocationsData) {
        try {
            await repository.save({
                zone: loc.zone,
                section: loc.section,
                neighborhood: loc.neighborhood,
                locationName: loc.locationName,
                address: loc.address,
                municipality: 'PARNAÍBA',
                state: 'PI',
            });
            inserted++;
        } catch (error) {
            console.log(`Erro ao inserir seção ${loc.section}: ${error.message}`);
        }
    }

    console.log(`${inserted} locais de votação inseridos (de ${votingLocationsData.length})`);

    // Mostrar resumo por bairro
    const result = await repository
        .createQueryBuilder('vl')
        .select('vl.neighborhood', 'neighborhood')
        .addSelect('COUNT(*)', 'count')
        .groupBy('vl.neighborhood')
        .orderBy('count', 'DESC')
        .getRawMany();

    console.log('\nSeções por bairro:');
    result.forEach((r: { neighborhood: string; count: string }) => {
        console.log(`  ${r.neighborhood}: ${r.count} seções`);
    });

    await dataSource.destroy();
    console.log('\nConexão encerrada');
}

seedVotingLocations().catch(console.error);
